<?php

namespace DoctrineProxies\__CG__;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class StudentAttendance extends \StudentAttendance implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'StudentAttendance' . "\0" . 'occupationType', '' . "\0" . 'StudentAttendance' . "\0" . 'occupationNumber', '' . "\0" . 'StudentAttendance' . "\0" . 'visitStatus', '' . "\0" . 'StudentAttendance' . "\0" . 'disciplineGroup', '' . "\0" . 'StudentAttendance' . "\0" . 'studentGroup', '' . "\0" . 'StudentAttendance' . "\0" . 'id', '' . "\0" . 'StudentAttendance' . "\0" . 'student', '' . "\0" . 'StudentAttendance' . "\0" . 'discipline_group'];
        }

        return ['__isInitialized__', '' . "\0" . 'StudentAttendance' . "\0" . 'occupationType', '' . "\0" . 'StudentAttendance' . "\0" . 'occupationNumber', '' . "\0" . 'StudentAttendance' . "\0" . 'visitStatus', '' . "\0" . 'StudentAttendance' . "\0" . 'disciplineGroup', '' . "\0" . 'StudentAttendance' . "\0" . 'studentGroup', '' . "\0" . 'StudentAttendance' . "\0" . 'id', '' . "\0" . 'StudentAttendance' . "\0" . 'student', '' . "\0" . 'StudentAttendance' . "\0" . 'discipline_group'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (StudentAttendance $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getOccupationType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOccupationType', []);

        return parent::getOccupationType();
    }

    /**
     * {@inheritDoc}
     */
    public function setOccupationType($occupationType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOccupationType', [$occupationType]);

        return parent::setOccupationType($occupationType);
    }

    /**
     * {@inheritDoc}
     */
    public function getOccupationNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOccupationNumber', []);

        return parent::getOccupationNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setOccupationNumber($occupationNumber)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOccupationNumber', [$occupationNumber]);

        return parent::setOccupationNumber($occupationNumber);
    }

    /**
     * {@inheritDoc}
     */
    public function isWasVisited()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isWasVisited', []);

        return parent::isWasVisited();
    }

    /**
     * {@inheritDoc}
     */
    public function setWasVisited($wasVisited)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWasVisited', [$wasVisited]);

        return parent::setWasVisited($wasVisited);
    }

    /**
     * {@inheritDoc}
     */
    public function getStudent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStudent', []);

        return parent::getStudent();
    }

    /**
     * {@inheritDoc}
     */
    public function setStudent($student)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStudent', [$student]);

        return parent::setStudent($student);
    }

    /**
     * {@inheritDoc}
     */
    public function getDisciplineGroup()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDisciplineGroup', []);

        return parent::getDisciplineGroup();
    }

    /**
     * {@inheritDoc}
     */
    public function setDisciplineGroup($discipline_group)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDisciplineGroup', [$discipline_group]);

        return parent::setDisciplineGroup($discipline_group);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

}
